- hosts: 127.0.0.1
  connection: local
  vars:
    apt_urls:
      - https://go.microsoft.com/fwlink/?LinkID=760868
      - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    apt_packages:
      - python3-pip
      - python3-venv
      - zsh
      - git
      - curl
      - solaar
      - tilix
      - gnome-tweaks
    oh_my_zsh_repos:
      - repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
      - repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    zsh_config:
      - url: https://raw.githubusercontent.com/JamesHaughey/linux_installs/master/dotfiles/.zshrc
        dest: ~/.zshrc
      - url: https://raw.githubusercontent.com/JamesHaughey/linux_installs/master/dotfiles/.p10k.zsh
        dest: ~/.p10k.zsh
    fonts:
      - MesloLGS%20NF%20Regular.ttf
      - MesloLGS%20NF%20Bold.ttf
      - MesloLGS%20NF%20Italic.ttf
      - MesloLGS%20NF%20Bold%20Italic.ttf
  tasks:
    # - name: Install from url
    #   become: yes
    #   remote_user: root
    #   apt:
    #     deb: "{{ item }}"
    #   loop: "{{ apt_urls }}"
      
    - name: Install from apt
      become: yes
      remote_user: root
      apt:
        name: "{{ apt_packages }}"
          
    # - name: Download install script
    #   get_url:
    #     url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    #     dest: ~/Downloads/0h-my-zsh-installer.sh
    #     mode: u+rwx
    # - name: Execute install script
    #   shell: ~/Downloads/0h-my-zsh-installer.sh
    # - name: Remove the install script
    #   file:
    #     path: ~/Downloads/0h-my-zsh-installer.sh
    #     state: absent
    - name: Clone powerlevel10k
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop: "{{ oh_my_zsh_repos }}"
    - name: Download zsh config files
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      loop: "{{ zsh_config }}"
    - name: Create fonts folder
      file:
        path: ~/.fonts/
        state: directory
        mode: "0755"
    - name: Download Fonts
      get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item }}"
        dest: "~/.fonts/{{ item }}"
      loop: "{{ fonts }}"
    - name: Set tiago user shell to zsh
      become: yes
      user:
        name: tiago
        shell: /bin/zsh
